# Dependencies
markdown:         redcarpet
highlighter:      pygment

# Permalinks
permalink:        pretty

# Setup
title:            The Last Patient
tagline:          'And how does that make you feel?'
description:      'Exploring the American psyche, horizontally from this ever-so-comfortable sofa. Web template based on the <a href="http://lanyon.getpoole.com/">lanyon</a> Jekyll theme.'
url:              http://thelastpatient.github.io

author:
  name:           'Ben Prince'
  # url:            https://twitter.com/mdo

paginate:         1

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/thelastpatient/thelastpatient.github.io

gems: [jekyll-paginate]
